### ISSUE TITLE
Button icon in Quasar UMD Demo breaks with fontawesome

### ISSUE THREAD

**Issue by tuhin-paul** [quasarframework/quasar-extras#18]
This is in reference to this Demo: https://jsfiddle.net/rstoenescu/waugrryy/ from UMD Starter Kit - CDN install section in this link: https://quasar-framework.org/guide/embedding-quasar.html

When I use fontawesome the icon is seen as a text instead of graphic.  
Demo here: https://jsfiddle.net/fd7puhtw/ 
I have not changed the code. Only replaced resource: https://unpkg.com/quasar-extras@1.0.2/material-icons/material-icons.css
with resource: https://unpkg.com/quasar-extras@1.0.2/fontawesome/fontawesome.css

Do I need to include something else here? My app already uses fontawesome so I'd want to use Quasar with that.

BTW, thank you so much for creating Quasar Framework. And thank you for your time in looking into this issue.

**Comment by rstoenescu** [comment]
Hi,

1. When you choose a combination it's best to check out: "$ quasar init -t umd <folder>" --> it will ask you a bunch of question and generate an index.html with all the style and script tags that you need.
2. Example for your case: https://jsfiddle.net/rstoenescu/qbd6jnuk/
  Note the script pointing to `https://unpkg.com/quasar-framework@^0.16.0/dist/umd/icons.fontawesome.umd.min.js` which tells Quasar to use Fontawesome for its own components.
3. The best leverage of browser's cache is to use the official CDN link for each icon library instead of pointing to quasar-extras's one.

Enjoy!

**Comment by tuhin-paul** [comment]
Thank you for the quick response!
